server.port=${PORT:8080}

spring.datasource.url=postgresql://sena:5xY1qFE9T9MjJDxLCQmmzwtuPcJXWNXj@dpg-dalv8irl550s73ck3j00-a/sistema_inventario_5h9n
spring.datasource.username=sena
spring.datasource.password=5xY1qFE9T9MjJDxLCQmmzwtuPcJXWNXj

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
Configuro conexión Render
